# Site settings
title: Guy Tennenholtz
description: Guy Tennenholtz Blog on Reinforcement Learning and Game Development
keywords: Reinforcement Learning, Game Development
author: Guy Tennenholtz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
